features:
  window_size: 5
  target_name_pairs:
    - ["formPTS", "Form"]
    - ["YC", "AVG_YC"]
    - ["RC", "AVG_RC"]
  h2h_pairs:
    - ["formPTS", "formH2H"]
    - ["Goals", "avg_H2H_goals"]
  previous_cols:
    ["PTS", "W", "D", "L", "GF", "GA", "SSN_YC", "SSN_RC", "AVG_SOT"]
  baseline:
    18
  rename:
    "PTS": "prevPTS"

# constants needed for the pipeline
pipeline:
  raw_data_dir: "./data/raw"
  cols: 
    [
      "Date", "HomeTeam", "FTHG", "HS", "HST", "HY", "HR", "HF",
      "AwayTeam", "FTAG", "AS", "AST", "AY", "AR", "AF", "FTR"
    ]
  # constants for writing / saving
  standings_dir: "./data/processed/debug/standings_yearly"
  starting_year: 2008
  standings_prefix: "standings"

  # team-match format
  team_match_dir: "./data/processed/debug/team_match_yearly"
  team_match_prefix: "team-match"

  # yearly short format
  yearly_dir: "./data/processed/debug/processed_yearly"
  yearly_prefix: "prem-data"

  # stacked (short) format
  short_stacked_dir: "./data/processed/inputs"
  short_stacked_filename: "stacked-short"

  # stacked (team-match) format
  team_match_stacked_dir: "./data/processed/inputs"
  team_match_stacked_filename: "stacked-team-match"

  # opponent features
  opp_features:
    ["YC", "RC", "Goals", "Form", "AVG_YC", "AVG_RC", "prevPTS", "W", "D", "L", ]
  
transformer:
  opp_features:
    [
      "Date","Opponent","YC", "RC", "Goals", "Form", "AVG_YC", "AVG_RC", "prevPTS",
      "GF", "GA", "SSN_YC", "SSN_RC", "AVG_SOT", "formH2H", "avg_H2H_goals"
    ]

model:
  nn:
    # constants here for neural network
    lr: 0.0005
    weight_decay: 0
    epochs: 100
    


