features:
  window_size: 5
  target_name_pairs:
    - ["formPTS", "Form"]
    - ["YC", "AVG_YC"]
    - ["RC", "AVG_RC"]
  h2h_pairs:
    - ["formPTS", "formH2H"]
    - ["Goals", "avg_H2H_goals"]
  previous_cols:
    ["PTS", "W", "D", "L", "GF", "GA", "SSN_YC", "SSN_RC", "AVG_SOT"]
  baseline:
    18
  rename:
    "PTS": "prevPTS"

# constants needed for the pipeline
pipeline:
  season_length: 380
  splits: [0.7, 0.1, 0.2]
  raw_data_dir: "./data/raw"
  cols: 
    [
      "Date", "HomeTeam", "FTHG", "HS", "HST", "HY", "HR", "HF",
      "AwayTeam", "FTAG", "AS", "AST", "AY", "AR", "AF", "FTR"
    ]
  # constants for writing / saving
  standings_dir: "./data/processed/debug/standings_yearly"
  starting_year: 2008
  standings_prefix: "standings"

  # team-match format
  team_match_dir: "./data/processed/debug/team_match_yearly"
  team_match_prefix: "team-match"

  # yearly short format
  yearly_dir: "./data/processed/debug/processed_yearly"
  yearly_prefix: "prem-data"

  # stacked (short) format
  short_stacked_dir: "./data/processed/inputs"
  short_stacked_filename: "stacked-short"

  # stacked (team-match) format
  team_match_stacked_dir: "./data/processed/inputs"
  team_match_stacked_filename: "stacked-team-match"

  # paths for train/val/test splits
  short_splits_dir: "./data/processed/inputs/short"
  team_match_splits_dir: "./data/processed/inputs/team-match"


  # opponent features
  opp_features:
    ["YC", "RC", "Goals", "Form", "AVG_YC", "AVG_RC", "prevPTS", "W", "D", "L", ]
  
transformer:
  opp_features:
    [
      "Date","Opponent","YC", "RC", "Goals", "Form", "AVG_YC", "AVG_RC", "prevPTS",
      "GF", "GA", "SSN_YC", "SSN_RC", "AVG_SOT", "formH2H", "avg_H2H_goals"
    ]

model:
  nn:
    split_props: [70,10,20]
    # constants here for neural network
    lr: 0.0005
    weight_decay: 0
    epochs: 100

    # feature columns
    features:
      # home team features
      - "YC_home"
      - "RC_home"
      - "Form_home"
      - "AVG_YC_home"
      - "AVG_RC_home"
      - "prevPTS_home"
      - "GF_home"
      - "GA_home"
      - "SSN_YC_home"
      - "SSN_RC_home"
      - "AVG_SOT_home"
      - "formH2H_home"
      - "avg_H2H_goals_home"
      # away team features
      - "YC_away"
      - "RC_away"
      - "Form_away"
      - "AVG_YC_away"
      - "AVG_RC_away"
      - "prevPTS_away"
      - "GF_away"
      - "GA_away"
      - "SSN_YC_away"
      - "SSN_RC_away"
      - "AVG_SOT_away"
      - "formH2H_away"
      - "avg_H2H_goals_away"

    labels:
      - "Goals_home"
      - "Goals_away"

    inter_dims: 64

    # paths for data
    processed: "./data/processed/inputs/stacked-short.csv" # BE SURE TO SET THIS TO PATH OF PROCESSED SHORT FORMAT DATA
    training_path: "./data/processed/inputs/short/training.csv"
    validation_path: "./data/processed/inputs/short/validation.csv"
    test_path: "./data/processed/inputs/short/test.csv



